var e = require("../../../../gateways/index-runtime-gateway"),
  t = e.getBootstrapData,
  r = e.getBootstrapLiteData,
  a = e.getDiyBootstrapData,
  i = e.getDiyMaterialsPage,
  o = e.getDiyMaterialsBundleData,
  s = e.resolveMaterialsByCodes,
  l = e.loadSchemes,
  n = e.saveSchemes,
  c = e.deleteSchemeById,
  d = e.loadSchemeById,
  g = e.getSchemeSharePayload,
  u = e.loadCartItems,
  h = e.saveCartItems,
  C = e.loginByWechat,
  m = e.getWechatAuthSession,
  A = e.loginByWechatPhone,
  y = e.logoutByWechat,
  P = e.hasWechatLoginToken,
  S = e.getWechatAuthProfile,
  D = e.scanMiniProgramWebLogin,
  B = e.confirmMiniProgramWebLogin,
  b = e.cancelMiniProgramWebLogin,
  E = e.listCheckoutOptions,
  O = e.previewCheckoutFromCheckedItems,
  _ = e.createOrderFromCheckedItems,
  p = e.createPaymentForOrder,
  I = e.getPaymentResult,
  W = e.listOrders,
  f = e.getOrderDetail,
  N = e.resolveWebPaySceneToken,
  M = e.cancelOrder,
  T = e.listOrderStatusLogs,
  k = e.getDefaultAddress,
  v = e.listAddresses,
  R = e.createAddress,
  L = e.updateAddress,
  Y = e.deleteAddress,
  H = e.setDefaultAddress,
  q = e.saveWechatAddress,
  w = e.getProfileDashboard,
  F = e.getContactConfig,
  x = e.syncWechatProfile,
  G = e.uploadProfileImage,
  U = e.createCreatorApplication,
  K = e.getCreatorPublishStatus,
  z = e.getCurrentCreatorApplication,
  Q = e.listCreatorEligibleOrderItems,
  V = e.getCreatorPanel,
  X = e.createCreatorWork,
  Z = e.listCreatorWorks,
  j = e.createWithdrawRequest,
  J = e.listWithdrawRequests,
  $ = e.createDistributorApplication,
  ee = e.getCurrentDistributorApplication,
  te = e.getDistributorPanel,
  re = e.listDistributorDownlines,
  ae = e.listDistributorEarnings,
  ie = e.getDistributorInvite,
  oe = e.listProfileNotifications,
  se = e.markProfileNotificationRead,
  le = e.getHelpCenterContent,
  ne = e.getContentBlockByCode,
  ce = e.getContentBlocksByCodes,
  de = e.getShipmentByOrderNo,
  ge = e.getAfterSalesByOrderNo,
  ue = e.confirmReceiveByOrderNo,
  he = e.createAfterSaleByOrderNo,
  Ce = e.fetchCreatorPublicFeed,
  me = require("../../../../utils/logger"),
  Ae = require("../../../../constants/businessRules"),
  ye = Ae.PHOTO_MIN_BEAD_COUNT,
  Pe = Ae.SCHEME_NAME_MIN_LENGTH,
  Se = Ae.SCHEME_NAME_MAX_LENGTH,
  De = require("../../../../constants/storageKeys").DIY_ENTRY_TRANSITION_KEY,
  Be =
    require("../../../../contracts/navigation/route-contract").normalizeIndexActiveTab,
  be = require("../../../../contracts/navigation/query-contract"),
  Ee = be.LEGACY_ROUTE_QUERY_KEYS,
  Oe = be.normalizeSharedSchemeQuery,
  _e = be.buildIndexSharePath,
  pe = be.buildV2DesignsPath,
  Ie =
    require("../../../../utils/navigation/navigate-with-fallback").navigateWithFallback;
module.exports = {
  getBootstrapData: t,
  getBootstrapLiteData: r,
  getDiyBootstrapData: a,
  getDiyMaterialsPage: i,
  getDiyMaterialsBundleData: o,
  resolveMaterialsByCodes: s,
  loadSchemes: l,
  saveSchemes: n,
  deleteSchemeById: c,
  loadSchemeById: d,
  getSchemeSharePayload: g,
  loadCartItems: u,
  saveCartItems: h,
  loginByWechat: C,
  getWechatAuthSession: m,
  loginByWechatPhone: A,
  logoutByWechat: y,
  hasWechatLoginToken: P,
  getWechatAuthProfile: S,
  scanMiniProgramWebLogin: D,
  confirmMiniProgramWebLogin: B,
  cancelMiniProgramWebLogin: b,
  listCheckoutOptions: E,
  previewCheckoutFromCheckedItems: O,
  createOrderFromCheckedItems: _,
  createPaymentForOrder: p,
  getPaymentResult: I,
  listOrders: W,
  getOrderDetail: f,
  resolveWebPaySceneToken: N,
  cancelOrder: M,
  listOrderStatusLogs: T,
  getDefaultAddress: k,
  listAddresses: v,
  createAddress: R,
  updateAddress: L,
  deleteAddress: Y,
  setDefaultAddress: H,
  saveWechatAddress: q,
  getProfileDashboard: w,
  getContactConfig: F,
  syncWechatProfile: x,
  uploadProfileImage: G,
  createCreatorApplication: U,
  getCreatorPublishStatus: K,
  getCurrentCreatorApplication: z,
  listCreatorEligibleOrderItems: Q,
  getCreatorPanel: V,
  createCreatorWork: X,
  listCreatorWorks: Z,
  createWithdrawRequest: j,
  listWithdrawRequests: J,
  createDistributorApplication: $,
  getCurrentDistributorApplication: ee,
  getDistributorPanel: te,
  listDistributorDownlines: re,
  listDistributorEarnings: ae,
  getDistributorInvite: ie,
  listProfileNotifications: oe,
  markProfileNotificationRead: se,
  getHelpCenterContent: le,
  getContentBlockByCode: ne,
  getContentBlocksByCodes: ce,
  getShipmentByOrderNo: de,
  getAfterSalesByOrderNo: ge,
  confirmReceiveByOrderNo: ue,
  createAfterSaleByOrderNo: he,
  fetchCreatorPublicFeed: Ce,
  PHOTO_MIN_BEAD_COUNT: ye,
  SCHEME_NAME_MIN_LENGTH: Pe,
  SCHEME_NAME_MAX_LENGTH: Se,
  DIY_ENTRY_TRANSITION_KEY: De,
  BASE_TRAY_SIZE: 366,
  MIN_TRAY_SIZE: 308,
  PHOTO_TRAY_SCALE: 2.2,
  normalizeIndexActiveTab: Be,
  LEGACY_ROUTE_QUERY_KEYS: Ee,
  normalizeSharedSchemeQuery: Oe,
  buildIndexSharePath: _e,
  buildV2DesignsPath: pe,
  navigateWithFallback: Ie,
  logger: me,
};
