module.exports = {
  RUNTIME_ENV_OVERRIDES: {
    develop: {
      apiBaseUrl: "https://example-develop.tcloudbaseapp.com/api",
      transport: "cloudCallContainer",
      cloudEnvId: "replace_with_develop_env_id",
      cloudRunService: "replace_with_cloudrun_service",
      cloudRunBasePath: "/api",
      cloudRunGatewayPath: "/container-replace_with_cloudrun_service",
      assetCdnBaseUrl: "https://example-develop.tcloudbaseapp.com/assets",
      profileAvatarUrl: "https://example-avatar-url",
      profileAvatarFallback: "/assets/icons/user-muted.svg",
      enableRemoteBootstrap: !0,
      enableRealLogin: !0,
      enableRealOrderFlow: !0,
      enableRemoteSchemeStorage: !0,
      enableRemoteCartStorage: !0,
      enableCreatorDashboardData: !1,
      enableStandaloneDiyPage: !0,
      enableStandaloneDiyPageHomeEntry: !0,
      enableStandaloneDiyPageBottomNavEntry: !0,
      enableStandaloneDiyPageProductApply: !0,
      enableStandaloneDiyPageProfileEntry: !0,
      enableStandaloneDiyPageShareEntry: !0,
      allowHttpFallbackWhenContainerFail: !1,
    },
    trial: {},
    release: {
      apiBaseUrl: "https://api.example.com/api",
      transport: "http",
      assetCdnBaseUrl: "https://assets.example.com",
      enableRealLogin: !0,
      enableRealOrderFlow: !0,
      enableRemoteSchemeStorage: !0,
      enableRemoteCartStorage: !0,
      enableStandaloneDiyPage: !0,
      enableStandaloneDiyPageHomeEntry: !0,
      enableStandaloneDiyPageBottomNavEntry: !0,
      enableStandaloneDiyPageProductApply: !0,
      enableStandaloneDiyPageProfileEntry: !0,
      enableStandaloneDiyPageShareEntry: !0,
    },
  },
};
