var e = require("../../../@babel/runtime/helpers/typeof"),
  t = require("../../index/modules/shared/runtime-shared"),
  a = t.BASE_TRAY_SIZE,
  r = t.PHOTO_TRAY_SCALE,
  i = require("../../../config/env").getRuntimeEnvConfig,
  n = require("../../index/modules/deps/lifecycle-deps"),
  o = n.buildGuideTabs,
  s = n.buildMeasureCards,
  l = n.buildOperationTips,
  d = n.buildSizeCompareItems,
  u = n.buildTutorialSlides,
  c = new Set(["home", "inspiration", "cart", "profile"]);
function y(e) {
  var t = String(e || "")
    .trim()
    .toLowerCase();
  return c.has(t) ? t : "";
}
module.exports = {
  createDiyInitialData: function (t) {
    var n = i(),
      c = t && "object" === e(t) ? t : {},
      p = l(),
      g = u();
    return {
      appLoaded: !0,
      loadProgress: 100,
      loadingStage: "diy_page_skeleton_ready",
      loadingStageStartedAt: 0,
      shellReadyAt: 0,
      dataSyncingAt: 0,
      interactiveAt: 0,
      activeTab: "diy",
      activePrimaryTab: "diy",
      navActiveTab: "diy",
      isStandaloneDiy: !0,
      routeSource: String(c.source || "").trim(),
      diyReturnTab: y(c.returnTab),
      isNavVisible: !1,
      assetCdnBaseUrl: n.assetCdnBaseUrl,
      assetUiBaseUrl: "/assets",
      shellPaddingTop: 38,
      shellPaddingBottom: 0,
      statusBarHeight: 20,
      safeAreaTop: 20,
      safeAreaBottomInset: 0,
      menuButtonRect: null,
      menuButtonTopPx: 20,
      menuButtonHeightPx: 32,
      isCompactScreen: !1,
      isNarrowScreen: !1,
      appBarLayerStyle: "",
      topMetaLayerStyle: "",
      topGuideLayerStyle: "",
      trayStageLayerStyle: "",
      floatingPhotoLayerStyle: "",
      floatingUndoLayerStyle: "",
      floatingBlindBoxLayerStyle: "",
      actionRowLayerStyle: "",
      searchRowLayerStyle: "",
      mainTabsLayerStyle: "",
      materialPanelLayerStyle: "",
      trayWrapperStyle: "",
      traySize: a,
      trayBaseStyle: "width: ".concat(a, "px; height: ").concat(a, "px;"),
      trayPhotoStyle: "width: "
        .concat(a, "px; height: ")
        .concat(a, "px; transform: translateY(0px) scale(")
        .concat(r, ");"),
      photoBrandStyle: "",
      photoShareStyle: "",
      photoMode: !1,
      standaloneDiyEntryMaskVisible: !0,
      standaloneDiySceneMasked: !0,
      trayBgs: [],
      bgIndex: 4,
      currentTrayBg: null,
      currentPattern: [],
      currentRenderPlan: [],
      currentSchemeName: "",
      forceRegen: 0,
      trayState: {
        beadsCount: 0,
        totalPrice: 0,
        totalPerimeter: 0,
        maxPerimeterMm: 300,
        isOverMaxPerimeter: !1,
        isStrung: !1,
        pattern: [],
        totalPriceText: "0.0",
        totalPerimeterCmText: "0.0",
      },
      mainCategories: [],
      currentSubCategories: [],
      mainCategory: "",
      menuCategory: "in_use",
      searchQuery: "",
      displayBeads: [],
      diyMaterialsLoading: !0,
      presets: [],
      presetCategories: [],
      presetCategory: "",
      filteredPresets: [],
      visibleFilteredPresets: [],
      inspirationRenderLimit: 6,
      inspirationRenderStep: 6,
      blindBoxPreparing: !1,
      blindBoxWarming: !1,
      strungPreparing: !1,
      blindBoxReadyCount: 0,
      blindBoxReplayCount: 0,
      userWrist: null,
      userWristText: "设置手围",
      wristSettingOpen: !1,
      wristDraftValue: 17,
      wristDraftValueDisplay: "17.0",
      wristMonitor: {
        status: "idle",
        msg: "设置手围后可查看佩戴贴合度",
        tone: "muted",
        rangeText: "",
        rangeTextCompact: "",
      },
      checkoutPreparing: !1,
      checkoutData: null,
      checkoutPreview: null,
      isCheckingOut: !1,
      isConfirmPaying: !1,
      checkoutAddressResolving: !1,
      checkoutOptionGroups: [],
      selectedCheckoutOptions: {},
      checkoutOptionRefreshing: !1,
      checkedCartCount: 0,
      checkedCartTotal: 0,
      checkedCartTotalText: "0.0",
      checkoutGoodsAmountText: "0.0",
      checkoutServiceAmountText: "0.0",
      checkoutFreightAmountText: "0.0",
      deliveryEtaText: "3",
      selectedAddress: null,
      addressList: [],
      showAddressManagerModal: !1,
      showAddressFormModal: !1,
      addressManagerLoading: !1,
      addressSubmitting: !1,
      addressFormMode: "create",
      editingAddressId: "",
      addressForm: {
        receiverName: "",
        receiverPhone: "",
        province: "",
        city: "",
        district: "",
        street: "",
        detail: "",
        postalCode: "",
        tag: "",
        isDefault: !0,
      },
      paymentFlowState: "IDLE",
      pendingPaymentOrderNo: "",
      pendingPaymentAmount: 0,
      pendingPaymentCreatedAt: 0,
      pendingPaymentSignature: "",
      diyPhotoSharePreparing: !1,
      diyPhotoShareReady: !1,
      savedSchemeShareStateMap: {},
      savedSchemes: [],
      savedSchemesLoading: !1,
      cartItems: [],
      cartHydrating: !1,
      namingPayload: null,
      namingValue: "",
      guideModalOpen: !1,
      guideTab: "tips",
      guideTabs: o(),
      operationTips: p,
      operationTipIndex: p.length ? 1 : 0,
      operationTipTotalText: String(p.length).padStart(2, "0"),
      currentOperationTip: p[0] || null,
      tutorialSlides: g,
      currentTutorialSlide: g[0] || null,
      tutorialStep: 1,
      measureCards: s("F"),
      measureGender: "F",
      sizeCompareItems: d(),
      toast: "",
      toastVisible: !1,
      diyConfirmModal: null,
      showDiyShareModal: !1,
      showProfileShareModal: !1,
      showDiySizeGuidePopup: !1,
      diySizeGuideImage: "/assets/guide/diy-size-guide.jpg",
      profileSharePattern: [],
      showContentModal: !1,
      contentModalType: "",
      contentModalTitle: "",
      contentModalLoading: !1,
      contentModalError: "",
      contentModalText: "",
      showPaymentSuccessPopup: !1,
      paymentSuccessPopupImageUrl: "",
      paymentSuccessPopupText: "",
      isLoggedIn: !1,
      authVerifying: !1,
      showProfileAuthPrompt: !1,
      profileAuthNickname: "",
      profileAuthAvatarUrl: "",
      profileAuthSubmitting: !1,
      profileAvatarUrl: n.profileAvatarUrl,
      profileAvatarFallback: n.profileAvatarFallback,
      profileNickname: "微信用户",
      profileUserId: 0,
      pendingWebLoginSceneToken: "",
      webLoginConfirmVisible: !1,
      webLoginConfirmLoading: !1,
      webLoginConfirmStatus: "",
      webLoginConfirmMessage: "",
      layoutOverlayEnabled: !0 === n.layoutOverlayEnabled,
      layoutOverlayOpacity: Number.isFinite(Number(n.layoutOverlayOpacity))
        ? Math.max(0, Math.min(100, Number(n.layoutOverlayOpacity)))
        : 38,
      layoutOverlayImageUrl: String(n.layoutOverlayImageUrl || "").trim(),
    };
  },
  normalizeDiyReturnTab: y,
};
